# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretserverCli < Formula
  desc "SecretServer.io CLI — enterprise secret management"
  homepage "https://secretserver.io"
  version "1.0.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afterdarksys/secretserver-cli/releases/download/v1.0.1/ss_1.0.1_darwin_amd64.tar.gz"
      sha256 "49582d272f7a03e89da2501518b2beb1ce652bc227e5fbe77dbb5c8651bf0771"

      define_method(:install) do
        bin.install "ss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afterdarksys/secretserver-cli/releases/download/v1.0.1/ss_1.0.1_darwin_arm64.tar.gz"
      sha256 "5c427f70cdf506325276f5ed3b59f39306dd027eb385477e4ea10522217ba513"

      define_method(:install) do
        bin.install "ss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afterdarksys/secretserver-cli/releases/download/v1.0.1/ss_1.0.1_linux_amd64.tar.gz"
      sha256 "f495f7e8eeffa9b28c95252b7d66a441354e06f872700c6d2513c3ecc4facad5"
      define_method(:install) do
        bin.install "ss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afterdarksys/secretserver-cli/releases/download/v1.0.1/ss_1.0.1_linux_arm64.tar.gz"
      sha256 "5e7431082095097912d216d726ddf99dfc5b01c0d2848b2c87237fa59990a518"
      define_method(:install) do
        bin.install "ss"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ss version")
  end
end
