# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretserverCli < Formula
  desc "SecretServer.io CLI — enterprise secret management"
  homepage "https://secretserver.io"
  version "1.0.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afterdarksys/secretserver-cli/releases/download/v1.0.0/ss_1.0.0_darwin_amd64.tar.gz"
      sha256 "a3a52f10ef84e00778cc0d578f5132446b5bc678ed0551b62c701e65a1d559cd"

      define_method(:install) do
        bin.install "ss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afterdarksys/secretserver-cli/releases/download/v1.0.0/ss_1.0.0_darwin_arm64.tar.gz"
      sha256 "67992fb4a3662d6bb0412c4240bd54afcd944a9d34d195c94cd3515cb915c6fa"

      define_method(:install) do
        bin.install "ss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afterdarksys/secretserver-cli/releases/download/v1.0.0/ss_1.0.0_linux_amd64.tar.gz"
      sha256 "828aff4ecd0a62578491bfc25a087cacad642f0eb211681f758ea61e447fd4c4"
      define_method(:install) do
        bin.install "ss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afterdarksys/secretserver-cli/releases/download/v1.0.0/ss_1.0.0_linux_arm64.tar.gz"
      sha256 "f028c3d2b2c59f2cf83ea09fbf0374311d9419a4167532f0e3df4dc275fff00b"
      define_method(:install) do
        bin.install "ss"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ss version")
  end
end
